language: python
python:
  - "3.5"

cache: pip3

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE stack_over_flow_app;' - U postgres
  - psql -c 'CREATE DATABASE test_db;' - U postgres
  - psql -c "CREATE USER stackOverflow WITH PASSWORD 'hello$$123';" -U postgres

install:
  - pip install -r requirements.txt
  
script:
    - py.test --cov=API
    - coverage report
    
after_success:
    - coveralls
